[linux_hosts]
wsl_local ansible_host=localhost ansible_connection=local

[windows_hosts]
win_local ansible_host=172.20.0.1

[linux_hosts:vars]
ansible_user=ansible_user
ansible_password=Pass@123
ansible_become_password=Pass@123
ansible_become_pass=Pass@123

[windows_hosts:vars]
ansible_user=ansible_user
ansible_password=Pass@123
ansible_connection=winrm
ansible_port=5985
ansible_winrm_scheme=http
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ntlm
