- name: Create group on Linux
  ansible.builtin.group:
    name: "{{ group }}"
    state: present
  become: yes
  when: ansible_os_family != "Windows"

- name: Create group on Windows
  ansible.windows.win_group:
    name: "{{ group }}"
    state: present
  when: ansible_os_family == "Windows"