# Linux
- name: Create user on Linux
  ansible.builtin.user:
    name: "{{ user }}"
    state: present
    create_home: yes
  become: yes
  when: ansible_os_family != "Windows"

# Windows
- name: Create user on Windows
  ansible.windows.win_user:
    name: "{{ user }}"
    password: "TempPassword123!"
    state: present
    password_never_expires: yes
  when: ansible_os_family == "Windows"