- name: Modify file on Linux
  ansible.builtin.lineinfile:
    path: "{{ file_path }}"
    line: "{{ content }}"
    create: yes
  become: yes
  when:
    - modify_file_flag | default(false)
    - ansible_os_family != "Windows"

- name: Modify file on Windows
  ansible.windows.win_shell: |
    Add-Content -Path "{{ file_path }}" -Value "{{ content }}"
  when:
    - modify_file_flag | default(false)
    - ansible_os_family == "Windows"