- name: Run command on Linux
  ansible.builtin.shell:
    cmd: "{{ cmd }}"
  become: yes
  when:
    - run_cmd | default(false)
    - ansible_os_family != "Windows"

- name: Run command on Windows
  ansible.windows.win_shell:
    cmd: "{{ cmd }}"
  when:
    - run_cmd | default(false)
    - ansible_os_family == "Windows"